## Oplossen van magische vierkanten
Het magische vierkant ziet er als volgt uit:  
\begin{array} {|r|r|}
\hline 5 &  &    \\
\hline   &  & 4  \\
\hline   &  & 6  \\
\hline
\end{array}

Allereerst wordt de tabel omgezet naar een matrix met behulp van numpy.


In [1]:
import numpy as np

# setting up the square

square = np.array([[5, 0, 0],
                   [0, 0, 4],
                   [0, 0, 6]])


Om de regels overzichtelijker op te kunnen schrijven krijgt elk element zijn eigen aanduiding:  
\begin{array} {|r|r|}
\hline x_1 & x_2 & x_3 \\
\hline x_4 & x_5 & x_6 \\
\hline x_7 & x_8 & x_9 \\
\hline
\end{array}

Om dit vierkant 'magisch' te krijgen gelden de volgende formules: 
$x_1 + x_2 + x_3 = t$  
$x_4 + x_5 + x_6 = t$  
$x_7 + x_8 + x_9 = t$  
$x_1 + x_4 + x_7 = t$  
$x_2 + x_5 + x_8 = t$  
$x_3 + x_6 + x_9 = t$  
$x_1 + x_5 + x_9 = t$  
$x_3 + x_5 + x_7 = t$  
$3x_5 = t$

In deze formules is $t$ gebruikt om de som aan te duiden.  
Om in deze formules ervoor te zorgen dat de variabele $t$ kan worden meegenomen
in de formule kunnen de formules als volgt worden herschreven: 

$x_1 + x_2 + x_3 - t = 0$  
$x_4 + x_5 + x_6 - t = 0$  
$x_7 + x_8 + x_9 - t = 0$  
$x_1 + x_4 + x_7 - t = 0$  
$x_2 + x_5 + x_8 - t = 0$  
$x_3 + x_6 + x_9 - t = 0$  
$x_1 + x_5 + x_9 - t = 0$  
$x_3 + x_5 + x_7 - t = 0$  
$3x_5 - t = 0$  

Om de regels tot een matrix om te zetten worden alle regels in een lijst gezet.  
Een regel bestaat uit een lijst van indexen.

In [2]:
# get all the values of the square in a list for easier searching
value_list = []
for x in square:
    for y in x:
        value_list.append(y)

# Get all the positions of the elements of the square for easier slicing
new_square = []
count = 0
for lst in square:
    count_list = []
    for x in lst:
        count_list.append(count)
        count += 1
    new_square.append(count_list)
slice_list = np.array(new_square)

# make a slice for all the rules as described above
rule_1 = slice_list[0]
rule_2 = slice_list[1]
rule_3 = slice_list[2]
rule_4 = slice_list[:, :1].flatten()
rule_5 = slice_list[:, 1:2].flatten()
rule_6 = slice_list[:, 2:3].flatten()
rule_7 = slice_list.diagonal()
rule_8 = np.fliplr(slice_list).diagonal()
rule_9 = [slice_list[1][1]]

# append all the rules into one list of rules
rules_list = [rule_1, rule_2, rule_3, rule_4,
             rule_5, rule_6, rule_7, rule_8]


Aangezien een rij opgeteld de waarde $t$ heeft, zal de som van de rij min die $t$ 0 moeten zijn.  
Wanneer hierna ook nog een element in het vierkant bekend is kan een formule ook als volgt worden omgezet:  
$x_1 = 5$  
$x_1 + x_2 + x_3 -t = 0$  
kan worden omgezet in:   
$5 + x_2 + x_3 - t = 0$  
$x_2 + x_3 - t = -5$  

Nu we de regels in een lijst hebben kan de numpy array worden omgezet in een matrix.  
Er wordt eerst over alle regels heengegaan, hierna wordt er geloopt over de lengte van de totale hoeveelheid cijfers.  
Als de variabele van de loop voorkomt in de regel wordt er een 1 teruggegeven, anderzijds wordt er een 0 teruggegeven
waneer de variabele niet in de loop voorkomt.  
Ook wordt tegelijkertijd de result vector aangepast.

In [3]:
matrix_A = []
result_vector = []
for rule in rules_list:
    row = []
    result = 0
    for element in range(len(value_list)):
        # if the element exists in the given rule
        if element in rule:
            # if the element already has a value in the square
            if value_list[element] > 0:
                row.append(0)
                result -= value_list[element]
            # if the element doesn't already have a value in the square
            else:
                row.append(1)
        else:
            row.append(0)
    # add -1 for the -t at the end
    row.append(-1)
    # push the result and row into their respective lists
    result_vector.append(result)
    matrix_A.append(row)


Alleen de laatste regel moet handmatig worden toegepast.  



In [4]:
# adding the last row manual
last_row = [0 for x in range(len(value_list))]
last_row.append(-1)
if value_list[rule_9[0]] > 0:
    last_row[rule_9[0]] = 0
    result_vector.append(0- (3 * value_list[rule_9[0]]))
else:
    last_row[rule_9[0]] = 3
    result_vector.append(0)
matrix_A.append(last_row)

# convert the lists into numpy arrays for processing
matrix_A = np.array(matrix_A)
# result_vector = np.transpose(np.array([result_vector]))
result_vector = np.array(result_vector)
    
# print the lists
print("Matrix A:")
print(matrix_A)
print("\nDe vector b van de resultaat:")
print(result_vector)


Matrix A:
[[ 0  1  1  0  0  0  0  0  0 -1]
 [ 0  0  0  1  1  0  0  0  0 -1]
 [ 0  0  0  0  0  0  1  1  0 -1]
 [ 0  0  0  1  0  0  1  0  0 -1]
 [ 0  1  0  0  1  0  0  1  0 -1]
 [ 0  0  1  0  0  0  0  0  0 -1]
 [ 0  0  0  0  1  0  0  0  0 -1]
 [ 0  0  1  0  1  0  1  0  0 -1]
 [ 0  0  0  0  3  0  0  0  0 -1]]

De vector b van de resultaat:
[ -5  -4  -6  -5   0 -10 -11   0   0]


Om de oplossing van de matrix te vinden wordt eerst de pseudo-inverse van de matrix berekend.  
Een $n \times n$ matrix is niet persé nodig om de pseudo-inverse te gebruiken.
Alleen het gebruik van dé echte inverse vereist een vierkante matrix.  
De determinant van de matrix is 0, dit houdt in dat een inverse van deze matrix niet bestaat.
Om alsnog tot een zo volledig mogelijk antwoord te komen wordt hier de pseudo-inverse gebruikt,
omdat voor deze methode de inverse noodzakelijk is.  

Allereerst wordt de pseudo-inverse berekend van de matrix.
Hierna wordt het dot product van de pseudo-inverse en de resultaat vector berekend.  
Uiteindelijk worden de waardes van de opgeloste vector ingevuld op de plaatsen in het vierkant waar
nog geen waardes staan om daarna het opgeloste vierkant uit te printen.


In [5]:
# calculate the pseudo-inverse of the matrix
pseudo_inverse = np.linalg.pinv(matrix_A)

# take the dot product of the pseudo inverse and the result vector
solve_vector = np.dot(pseudo_inverse, result_vector)
solve_vector = list(solve_vector)

# round all the numbers to .1 accuracy
for x in range(0, len(solve_vector)):
    solve_vector[x] = round(solve_vector[x], 2)

# save the total sum number
total_number = solve_vector.pop()

# reshape the vector as a n x n matrix
solve_vector = np.reshape(solve_vector, (3, 3))

# append all the values that don't already exist
check_square = list(square)
solved_square = []
for row in range(0, len(check_square)):
    for num in range(0, len(check_square[0])):
        if check_square[row][num] > 0:
            solved_square.append(check_square[row][num])
        else:
            solved_square.append(solve_vector[row][num])

# reshape the square and print all the info
solved_square = np.reshape(solved_square, (3, 3))
print("The solved square:\n{0}\n".format(solved_square))
print("The side sum is: {0}".format(total_number))




The solved square:
[[5.  5.  6.5]
 [7.  5.5 4. ]
 [4.5 6.  6. ]]

The side sum is: 16.5
