## Oplossen van magische vierkanten
Het magische vierkant ziet er als volgt uit:  
\begin{array} {|r|r|}
\hline 5 &  &    \\
\hline   &  & 4  \\
\hline   &  & 6  \\
\hline
\end{array}

Allereerst wordt de tabel omgezet naar een matrix met behulp van numpy.


In [7]:
import numpy as np

# setting up the square

square = np.array([[0, 7, 0],
                   [0, 5, 0],
                   [0, 3, 0]])


Om de regels overzichtelijker op te kunnen schrijven krijgt elk element zijn eigen aanduiding:  
\begin{array} {|r|r|}
\hline x_1 & x_2 & x_3 \\
\hline x_4 & x_5 & x_6 \\
\hline x_7 & x_8 & x_9 \\
\hline
\end{array}

Om dit vierkant 'magisch' te krijgen gelden de volgende formules: 
$x_1 + x_2 + x_3 = t$  
$x_4 + x_5 + x_6 = t$  
$x_7 + x_8 + x_9 = t$  
$x_1 + x_4 + x_7 = t$  
$x_2 + x_5 + x_8 = t$  
$x_3 + x_6 + x_9 = t$  
$x_1 + x_5 + x_9 = t$  
$x_3 + x_5 + x_7 = t$  
$3x_5 = t$

In deze formules is $t$ gebruikt om de som aan te duiden.  
Om in deze formules ervoor te zorgen dat de variabele $t$ kan worden meegenomen
in de formule kunnen de formules als volgt worden herschreven: 

$x_1 + x_2 + x_3 - t = 0$  
$x_4 + x_5 + x_6 - t = 0$  
$x_7 + x_8 + x_9 - t = 0$  
$x_1 + x_4 + x_7 - t = 0$  
$x_2 + x_5 + x_8 - t = 0$  
$x_3 + x_6 + x_9 - t = 0$  
$x_1 + x_5 + x_9 - t = 0$  
$x_3 + x_5 + x_7 - t = 0$  
$3x_5 - t = 0$  

Om de regels tot een matrix om te zetten worden alle regels in een lijst gezet.  
Een regel bestaat uit een lijst van indexen.

In [8]:
# get all the values of the square in a list for easier searching
value_list = []
for x in square:
    for y in x:
        value_list.append(y)

# Get all the positions of the elements of the square for easier slicing
new_square = []
count = 0
for lst in square:
    count_list = []
    for x in lst:
        count_list.append(count)
        count += 1
    new_square.append(count_list)
slice_list = np.array(new_square)

# make a slice for all the rules as described above
rule_1 = slice_list[0]
rule_2 = slice_list[1]
rule_3 = slice_list[2]
rule_4 = slice_list[:, :1].flatten()
rule_5 = slice_list[:, 1:2].flatten()
rule_6 = slice_list[:, 2:3].flatten()
rule_7 = slice_list.diagonal()
rule_8 = np.fliplr(slice_list).diagonal()
rule_9 = [slice_list[1][1]]

# append all the rules into one list of rules
rules_list = [rule_1, rule_2, rule_3, rule_4,
             rule_5, rule_6, rule_7, rule_8]


Aangezien een rij opgeteld de waarde $t$ heeft, zal de som van de rij min die $t$ 0 moeten zijn.  
Wanneer hierna ook nog een element in het vierkant bekend is kan een formule ook als volgt worden omgezet:  
$x_1 = 5$  
$x_1 + x_2 + x_3 -t = 0$  
kan worden omgezet in:   
$5 + x_2 + x_3 - t = 0$  
$x_2 + x_3 - t = -5$  

Nu we de regels in een lijst hebben kan de numpy array worden omgezet in een matrix.  
Er wordt eerst over alle regels heengegaan, hierna wordt er geloopt over de lengte van de totale hoeveelheid cijfers.  
Als de variabele van de loop voorkomt in de regel wordt er een 1 teruggegeven, anderzijds wordt er een 0 teruggegeven
waneer de variabele niet in de loop voorkomt.  
Ook wordt tegelijkertijd de result vector aangepast.

In [9]:
matrix_A = []
result_vector = []
for rule in rules_list:
    row = []
    result = 0
    for element in range(len(value_list)):
        # if the element exists in the given rule
        if element in rule:
            # if the element already has a value in the square
            if value_list[element] > 0:
                row.append(0)
                result -= value_list[element]
            # if the element doesn't already have a value in the square
            else:
                row.append(1)
        else:
            row.append(0)
    # add -1 for the -t at the end
    row.append(-1)
    # push the result and row into their respective lists
    result_vector.append(result)
    matrix_A.append(row)


Alleen de laatste regel moet handmatig worden toegepast.  



In [10]:
# adding the last row manual
last_row = [0 for x in range(len(value_list))]
last_row.append(-1)
if value_list[rule_9[0]] > 0:
    last_row[rule_9[0]] = 0
    result_vector.append(0- (3 * value_list[rule_9[0]]))
else:
    last_row[rule_9[0]] = 3
    result_vector.append(0)
matrix_A.append(last_row)

# convert the lists into numpy arrays for processing
matrix_A = np.array(matrix_A)
# result_vector = np.transpose(np.array([result_vector]))
result_vector = np.array(result_vector)
    
# print the lists
print("Matrix A:")
print(matrix_A)
print("\nDe vector b van de resultaat:")
print(result_vector)


Matrix A:
[[ 1  0  1  0  0  0  0  0  0 -1]
 [ 0  0  0  1  0  1  0  0  0 -1]
 [ 0  0  0  0  0  0  1  0  1 -1]
 [ 1  0  0  1  0  0  1  0  0 -1]
 [ 0  0  0  0  0  0  0  0  0 -1]
 [ 0  0  1  0  0  1  0  0  1 -1]
 [ 1  0  0  0  0  0  0  0  1 -1]
 [ 0  0  1  0  0  0  1  0  0 -1]
 [ 0  0  0  0  0  0  0  0  0 -1]]

De vector b van de resultaat:
[ -7  -5  -3   0 -15   0  -5  -5 -15]


Aangezien de gebruikte functies in numpy alleen werken met een $n \times n$ matrix moet één kolom worden verwijderd.  
In de matrix wordt er bij de volgende functie naar een kolom met alleen maar 0 waardes gezocht.  
Hierna wordt de kolom verwijderd en de nieuwe matrix teruggegeven tezamen met de plaats van de verwijderde kolom.


In [11]:
def delete_column(chosen_matrix):
    """Checks for an empty column and deletes one"""
    
    chosen_matrix = list(chosen_matrix)
    col_number = 0
    
    # 
    for col in range(0,len(chosen_matrix[0])):
        is_zero_column = True
        for row in range(0,len(chosen_matrix)):
            if chosen_matrix[row][col_number] != 0:
                is_zero_column = False
                break
        # the column is a zero-column
        if is_zero_column:
            chosen_matrix = np.array(chosen_matrix)
            chosen_col = [x for x in range(0, len(chosen_matrix) + 1) if x != col_number]
            return chosen_matrix[:,chosen_col], col_number

        # search the next column
        col_number += 1

# printing the shape of the matrix
print("Shape of the matrix before erase:\n{0}\n".format(np.shape(matrix_A)))

# erase a column and return the new values into their respective variables
changed_matrix = delete_column(matrix_A)
matrix_B = changed_matrix[0]
deleted_col = changed_matrix[1]
print("Shape of matrix after erase:\n{0}".format(np.shape(matrix_B)))


Shape of the matrix before erase:
(9, 10)

Shape of matrix after erase:
(9, 9)


Om de oplossing van de matrix te vinden wordt eerst de pseudo-inverse van de matrix berekend.  
Hierna wordt het dot product van de pseudo-inverse en de resultaat vector berekend.  
Aangezien er uit de matrix één kolom verwijderd is, wordt deze er later bij de oplossings vector bijgevoegd.  
Hierdoor kan er tegelijkertijd over de oplossingsvector en het originele vierkant worden geloopt, hierbij
wordt er eerst gecheckt of er al een waarde voor bestaat, wanneer dit niet zo is wordt de waarde van
de oplossings vector genomen.


In [12]:
# calculate the pseudo-inverse of the matrix
pseudo_inverse = np.linalg.pinv(matrix_B)

# take the dot product of the pseudo inverse and the result vector
solve_vector = np.dot(pseudo_inverse, result_vector)
solve_vector = list(solve_vector)

# add the deleted column back
solve_vector.insert(deleted_col, 0)

# round all the numbers to .1 accuracy
for x in range(0, len(solve_vector)):
    solve_vector[x] = round(solve_vector[x], 2)

# save the total sum number
total_number = solve_vector.pop()

# reshape the vector as a n x n matrix
solve_vector = np.reshape(solve_vector, (3, 3))

# 
check_square = list(square)
solved_square = []
for row in range(0, len(check_square)):
    for num in range(0, len(check_square[0])):
        if check_square[row][num] > 0:
            solved_square.append(check_square[row][num])
        else:
            solved_square.append(solve_vector[row][num])

# reshape the square and print all the info
solved_square = np.reshape(solved_square, (3, 3))
print("The solved square:\n{0}\n".format(solved_square))
print("The side sum is: {0}".format(total_number))



The solved square:
[[4. 7. 4.]
 [5. 5. 5.]
 [6. 3. 6.]]

The side sum is: 15.0
